### ISSUE TITLE
Link is just "file:///" after build

### ISSUE THREAD

**Issue by tohuw** [zhenyong/hexo-filter-file-link#2]
When I load this plugin (v1.0.4) on Hexo 3.7.1, the link simply turns into "file:///" instead of the right URL for the post.

My implementation looks like this: `[My Hello World post](file://hello-world.md)`, from a post in the same folder as hello-world.md. [The repo for this case is here](https://gitlab.com/tohuwnet-hexo/tohuwnet/tree/b1a3ec087b0cc2784dd2971ed5c60400291f6e3e), you can download it by using the button in the upper left if you wish. The test is in the post "my-test-post.md". Thank you!

**Comment by tohuw** [comment]
Per my comment in #3, looks like the error message on build is Chinese only, and reads "Can't match the following articles". I wonder why it can't match it?

**Comment by zhenyong** [comment]
Update and try.

BTW, I think there should be a better way than this plugin. ^_^

**Comment by tohuw** [comment]
Indeed, it seems to work now for my original test case. However, I uncovered a new, related issue that ought to be pretty easy to fix: see #4
